{"variants":[{"paths":["\/documentation\/niohttp2\/http2errorcode\/internalerror"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/HTTP2ErrorCode\/internalError"},"metadata":{"modules":[{"name":"NIOHTTP2"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8NIOHTTP214HTTP2ErrorCodeV","text":"HTTP2ErrorCode","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","roleHeading":"Type Property","title":"internalError","externalID":"s:8NIOHTTP214HTTP2ErrorCodeV08internalC0ACvpZ"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Linux"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HTTP2ErrorCode","preciseIdentifier":"s:8NIOHTTP214HTTP2ErrorCodeV","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/HTTP2ErrorCode","kind":"typeIdentifier"}]}]}],"abstract":[{"type":"text","text":"The endpoint encountered an unexpected internal error."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/HTTP2ErrorCode"]]},"references":{"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/HTTP2ErrorCode":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HTTP2ErrorCode"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HTTP2ErrorCode"}],"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/HTTP2ErrorCode","title":"HTTP2ErrorCode","abstract":[{"type":"text","text":"An HTTP\/2 error code."}],"url":"\/documentation\/niohttp2\/http2errorcode"},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2":{"type":"topic","url":"\/documentation\/niohttp2","kind":"symbol","title":"NIOHTTP2","abstract":[],"role":"collection","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2"},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/HTTP2ErrorCode/internalError":{"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/HTTP2ErrorCode\/internalError","url":"\/documentation\/niohttp2\/http2errorcode\/internalerror","title":"internalError","kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HTTP2ErrorCode","kind":"typeIdentifier","preciseIdentifier":"s:8NIOHTTP214HTTP2ErrorCodeV"}],"abstract":[{"text":"The endpoint encountered an unexpected internal error.","type":"text"}],"role":"symbol"}}}